"use client";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sideBar";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
         
          antialiased flex`}
      >
        <SessionProvider>
          <Toaster position="top-right" />
          <SideBar />
        </SessionProvider>
        <main className="flex-1 p-6 bg-gray-50 min-h-screen">{children}</main>
      </body>
    </html>
  );
}
