import Timer from "@/components/Timer";
import React from "react";
import type { Metadata } from "next";
import { DataTableDemo } from "../projects/data-table";

export const metadata: Metadata = {
  title: "Dashboard - Time Tracker",
  description: "Generated by create next app",
};

const Dashboard = () => {
  return (
    <>
      <header>
        <h1 className="text-3xl mb-6 text-black">Dashboard</h1>
      </header>
      <div className="grid grid-cols-[auto_1fr] gap-6">
        <Timer />
        <div className="bg-white shadow-md p-6 rounded-lg row-span-2">
          <h2 className="text-3xl mb-4">Project Overview</h2>
          <DataTableDemo />
        </div>
        <Timer />
      </div>
    </>
  );
};

export default Dashboard;
